// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3JZmgHVaHVrOGmiGbmW0Mh7cXXFE7g8A',
    appId: '1:131912837690:web:7b8e5dab9719a1d835a303',
    messagingSenderId: '131912837690',
    projectId: 'student-management-syste-1a5b6',
    authDomain: 'student-management-syste-1a5b6.firebaseapp.com',
    storageBucket: 'student-management-syste-1a5b6.firebasestorage.app',
    measurementId: 'G-Y1H4PW64W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdTlR-Paaxnnn9LwDqmbDa1gYHcJQ3rug',
    appId: '1:131912837690:android:b31fa0e0c2c9b32e35a303',
    messagingSenderId: '131912837690',
    projectId: 'student-management-syste-1a5b6',
    storageBucket: 'student-management-syste-1a5b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgL0IZK1emoGfpJbYQ5BmGRwsIQH3A13k',
    appId: '1:131912837690:ios:6df418a74913484435a303',
    messagingSenderId: '131912837690',
    projectId: 'student-management-syste-1a5b6',
    storageBucket: 'student-management-syste-1a5b6.firebasestorage.app',
    iosBundleId: 'com.example.qrApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgL0IZK1emoGfpJbYQ5BmGRwsIQH3A13k',
    appId: '1:131912837690:ios:6df418a74913484435a303',
    messagingSenderId: '131912837690',
    projectId: 'student-management-syste-1a5b6',
    storageBucket: 'student-management-syste-1a5b6.firebasestorage.app',
    iosBundleId: 'com.example.qrApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3JZmgHVaHVrOGmiGbmW0Mh7cXXFE7g8A',
    appId: '1:131912837690:web:35cc69b7839f1dd235a303',
    messagingSenderId: '131912837690',
    projectId: 'student-management-syste-1a5b6',
    authDomain: 'student-management-syste-1a5b6.firebaseapp.com',
    storageBucket: 'student-management-syste-1a5b6.firebasestorage.app',
    measurementId: 'G-153ZSMMH29',
  );
}
